export const countryArr = [
    'afghanistan.png',
    'albania.png',
    'algeria.png',
    'andorra.png',
    'angola.png',
    'antarctica.png',
    'antigua and barbuda.png',
    'argentina.png',
    'armenia.png',
    'aruba.png',
    'australia.png',
    'austria.png',
    'azerbaijan.png',
    'bahrain.png',
    'bangladesh.png',
    'belarus.png',
    'belgium.png',
    'belize.png',
    'benin.png',
    'bermuda.png',
    'bhutan.png',
    'bolivia.png',
    'bosnia and herzegovina.png',
    'botswana.png',
    'brazil.png',
    'brunei.png',
    'bulgaria.png',
    'burkina faso.png',
    'burundi.png',
    'cambodia.png',
    'cameroon.png',
    'canada.png',
    'central african republic.png',
    'chad.png',
    'chile.png',
    'china.png',
    'christmas island.png',
    'colombia.png',
    'costa rica.png',
    "cote d'ivoire.png",
    'croatia.png',
    'cuba.png',
    'curacao.png',
    'czechia.png',
    'democratic republic of the congo.png',
    'denmark.png',
    'djibouti.png',
    'dominica.png',
    'dominican republic.png',
    'east timor.png',
    'ecuador.png',
    'egypt.png',
    'el salvador.png',
    'equatorial guinea.png',
    'eritrea.png',
    'estonia.png',
    'eswatini.png',
    'ethiopia.png',
    'falkland islands.png',
    'faroe islands.png',
    'finland.png',
    'france.png',
    'french guiana.png',
    'gabon.png',
    'georgia.png',
    'germany.png',
    'ghana.png',
    'gibraltar.png',
    'greece.png',
    'greenland.png',
    'guam.png',
    'guatemala.png',
    'guinea.png',
    'guinea-bissau.png',
    'guyana.png',
    'haiti.png',
    'honduras.png',
    'hungary.png',
    'iceland.png',
    'india.png',
    'indonesia.png',
    'iran.png',
    'iraq.png',
    'ireland.png',
    'israel.png',
    'italy.png',
    'japan.png',
    'jordan.png',
    'kazakhstan.png',
    'kenya.png',
    'laos.png',
    'latvia.png',
    'lebanon.png',
    'lesotho.png',
    'liberia.png',
    'libya.png',
    'liechtenstein.png',
    'lithuania.png',
    'luxembourg.png',
    'madagascar.png',
    'malaysia.png',
    'mali.png',
    'malta.png',
    'mauritania.png',
    'mexico.png',
    'moldova.png',
    'monaco.png',
    'mongolia.png',
    'montenegro.png',
    'morocco.png',
    'mozambique.png',
    'myanmar.png',
    'namibia.png',
    'nepal.png',
    'netherlands.png',
    'new zealand.png',
    'nicaragua.png',
    'niger.png',
    'nigeria.png',
    'north korea.png',
    'north macedonia.png',
    'norway.png',
    'oman.png',
    'pakistan.png',
    'panama.png',
    'papua new guinea.png',
    'paraguay.png',
    'peru.png',
    'philippines.png',
    'poland.png',
    'portugal.png',
    'puerto rico.png',
    'qatar.png',
    'republic of the congo.png',
    'russia.png',
    'rwanda.png',
    'serbia.png',
    'sierra leone.png',
    'singapore.png',
    'slovakia.png',
    'slovenia.png',
    'somalia.png',
    'south africa.png',
    'south korea.png',
    'south sudan.png',
    'spain.png',
    'sri lanka.png',
    'sudan.png',
    'suriname.png',
    'svalbard.png',
    'sweden.png',
    'switzerland.png',
    'syria.png',
    'taiwan.png',
    'tajikistan.png',
    'tanzania.png',
    'thailand.png',
    'the bahamas.png',
    'the gambia.png',
    'togo.png',
    'tunisia.png',
    'turkey.png',
    'turkmenistan.png',
    'uganda.png',
    'ukraine.png',
    'united arab emirates.png',
    'united kingdom.png',
    'united states.png',
    'uruguay.png',
    'uzbekistan.png',
    'venezuela.png',
    'vietnam.png',
    'western sahara.png',
    'yemen.png',
    'zambia.png',
    'zimbabwe.png',
    ]