export { default as Contacts } from './contacts/contacts'
export { default as Intro } from './intro/intro'
export { default as Navbar } from './navbar/navbar'
export { default as Skills } from './skills/skills'
export { default as Projects } from './projects/projects'
export { default as AboutMe } from './aboutMe/AboutMe'
export { default as Menu } from './menu/menu'